# vi:syntax=yaml
name: Build and Push to ECR
on:
  # This provides a button in the actions tab to run this on demand
  workflow_dispatch:
  push:
    # You can set these branches to any that you want to build and push images from
    branches:
      [ $default-branch ]
    # Set paths you can edit without triggering automated builds
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-push-ecr:
    strategy:
      matrix:
        # If you need to push to multiple accounts, you can add them here
        aws_account_ids: ["868468680417"] # glgapp account

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup ECR OIDC Credentials
        id: aws-setup
        uses: glg/setup-ecr-aws-oidc@main
        with:
          aws_account_id: ${{ matrix.aws_account_ids }}

      # Builds a docker image from ./dockerfile, and pushes it to our ECR repository
      - uses: glg/build-and-push@main
        with:
          ecr_uri: ${{ steps.aws-setup.outputs.ecr_uri }}
          # Uncomment if you are build you image in glgapp account and want to push the image to AWS China, it is only applicable for glgapp account.
          # sync_to_aws_china: true
          # Uncomment if you have private repo dependancies in your package.json
          # github_ssh_key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          # Uncomment if you have private package dependancies in your package.json
          # github_packages_token: ${{secrets.GH_PACKAGE_REGISTRY_READ_TOKEN}}
